using ConfigureServiceExample.Services;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddSingleton<ILog, Log>();

var app = builder.Build();

app.Run(async (context) =>
{
    var logger= app.Services.GetRequiredService<ILog>();
    logger.WriteLog("Logged line \n");
    await context.Response.WriteAsync("This text was generated by the middleware.");
});

app.Run();
