var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.Use(async (context, next) =>
{
    await context.Response.WriteAsync("This text was generated by the app.Use middleware. Request path is: " + context.Request.Path.Value + "  \n");
    await next.Invoke();
});

app.Run( async (context) =>
{
    await context.Response.WriteAsync("This text was generated by the app.run middleware.");
});

app.Run();


