var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.UseStaticFiles();

app.Run(async (context) =>
{
    await context.Response.WriteAsync("This text was generated by middleware.");
});

app.Run();